//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la nota es inválido.
        /// </summary>
        internal static string ActivityNote_Note_Invalid {
            get {
                return ResourceManager.GetString("ActivityNote_Note_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string ActivityNote_Note_Required {
            get {
                return ResourceManager.GetString("ActivityNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha entrada no puede ser menor o igual que hoy.
        /// </summary>
        internal static string Activity_ActivityDate_EarlierThanCurrentDate {
            get {
                return ResourceManager.GetString("Activity_ActivityDate_EarlierThanCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tiempo que ha entrado es inválido.
        /// </summary>
        internal static string Activity_ActivityTime_Invalid {
            get {
                return ResourceManager.GetString("Activity_ActivityTime_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la sección de detalles es inválido.
        /// </summary>
        internal static string Activity_Details_Invalid {
            get {
                return ResourceManager.GetString("Activity_Details_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localización que ha entrado es inválida.
        /// </summary>
        internal static string Activity_Location_Invalid {
            get {
                return ResourceManager.GetString("Activity_Location_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El propósito de la actividad es inválido.
        /// </summary>
        internal static string Activity_Purpose_Invalid {
            get {
                return ResourceManager.GetString("Activity_Purpose_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el propósito de esta actividad.
        /// </summary>
        internal static string Activity_Purpose_Required {
            get {
                return ResourceManager.GetString("Activity_Purpose_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título entrado no es válido.
        /// </summary>
        internal static string Activity_Title_Invalid {
            get {
                return ResourceManager.GetString("Activity_Title_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el título de esta actividad.
        /// </summary>
        internal static string Activity_Title_Required {
            get {
                return ResourceManager.GetString("Activity_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido del comentario que ha entrado es inválido.
        /// </summary>
        internal static string Feedback_Feedback_Invalid {
            get {
                return ResourceManager.GetString("Feedback_Feedback_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su comentario.
        /// </summary>
        internal static string Feedback_Feedback_Required {
            get {
                return ResourceManager.GetString("Feedback_Feedback_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El enlace del documento es inválido.
        /// </summary>
        internal static string Media_MediaPath_Invalid {
            get {
                return ResourceManager.GetString("Media_MediaPath_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el enlace de este medio.
        /// </summary>
        internal static string Media_MediaPath_Required {
            get {
                return ResourceManager.GetString("Media_MediaPath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El título del documento es inválido.
        /// </summary>
        internal static string Media_MediaTitle_Invalid {
            get {
                return ResourceManager.GetString("Media_MediaTitle_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la misión de la entidad de alcance es inválido.
        /// </summary>
        internal static string OutreachEntityDetail_Mission_Invalid {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Mission_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado la misión de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Mission_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Mission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de los objetivos de la entidad de alcance es inválido.
        /// </summary>
        internal static string OutreachEntityDetail_Objectives_Invalid {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Objectives_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado los objetivos de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Objectives_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Objectives_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la entidad de alcance es inválido.
        /// </summary>
        internal static string OutreachEntityDetail_OutreachEntityName_Invalid {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_OutreachEntityName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el nombre de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_OutreachEntityName_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_OutreachEntityName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la visión de la entidad de alcance es inválido.
        /// </summary>
        internal static string OutreachEntityDetail_Vision_Invalid {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Vision_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado la visión de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Vision_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Vision_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del recurso es inválido.
        /// </summary>
        internal static string Resource_ResourceName_Invalid {
            get {
                return ResourceManager.GetString("Resource_ResourceName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un nombre para este recurso.
        /// </summary>
        internal static string Resource_ResourceName_Required {
            get {
                return ResourceManager.GetString("Resource_ResourceName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la nota es inválido.
        /// </summary>
        internal static string SchoolNote_Note_Invalid {
            get {
                return ResourceManager.GetString("SchoolNote_Note_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string SchoolNote_Note_Required {
            get {
                return ResourceManager.GetString("SchoolNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado una dirección para esta escuela.
        /// </summary>
        internal static string School_Address_Required {
            get {
                return ResourceManager.GetString("School_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número telefónico de la escuela es inválido.
        /// </summary>
        internal static string School_PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("School_PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un número telefónico para esta escuela.
        /// </summary>
        internal static string School_PhoneNumber_Required {
            get {
                return ResourceManager.GetString("School_PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la escuelas es inválido.
        /// </summary>
        internal static string School_SchoolName_Invalid {
            get {
                return ResourceManager.GetString("School_SchoolName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el nombre de la escuela.
        /// </summary>
        internal static string School_SchoolName_Required {
            get {
                return ResourceManager.GetString("School_SchoolName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número de secuencia de la escuela es inválido.
        /// </summary>
        internal static string School_SchoolSequenceNumber_Invalid {
            get {
                return ResourceManager.GetString("School_SchoolSequenceNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el numero de identificación para esta escuela.
        /// </summary>
        internal static string School_SchoolSequenceNumber_Required {
            get {
                return ResourceManager.GetString("School_SchoolSequenceNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una escuela con ese numéro de identificación.
        /// </summary>
        internal static string School_SchoolSequenceNumber_Unique {
            get {
                return ResourceManager.GetString("School_SchoolSequenceNumber_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre del edificio es inválido.
        /// </summary>
        internal static string Unit_Building_Invalid {
            get {
                return ResourceManager.GetString("Unit_Building_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un edificio para esta unidad.
        /// </summary>
        internal static string Unit_Building_Required {
            get {
                return ResourceManager.GetString("Unit_Building_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La extensión entrada es inválida.
        /// </summary>
        internal static string Unit_Extension_Invalid {
            get {
                return ResourceManager.GetString("Unit_Extension_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número telefónico de la unidad es inválido.
        /// </summary>
        internal static string Unit_PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("Unit_PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un número telefónico para esta unidad.
        /// </summary>
        internal static string Unit_PhoneNumber_Required {
            get {
                return ResourceManager.GetString("Unit_PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La oficina o salón entrado es inválido.
        /// </summary>
        internal static string Unit_RoomNumber_Invalid {
            get {
                return ResourceManager.GetString("Unit_RoomNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado una oficina o salón para esta unidad.
        /// </summary>
        internal static string Unit_RoomNumber_Required {
            get {
                return ResourceManager.GetString("Unit_RoomNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre de la unidad es inválido.
        /// </summary>
        internal static string Unit_UnitName_Invalid {
            get {
                return ResourceManager.GetString("Unit_UnitName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un nombre para esta unidad.
        /// </summary>
        internal static string Unit_UnitName_Required {
            get {
                return ResourceManager.GetString("Unit_UnitName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su nombre es inválido.
        /// </summary>
        internal static string UserDetail_FirstName_Invalid {
            get {
                return ResourceManager.GetString("UserDetail_FirstName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su nombre.
        /// </summary>
        internal static string UserDetail_FirstName_Required {
            get {
                return ResourceManager.GetString("UserDetail_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su género.
        /// </summary>
        internal static string UserDetail_Gender_Required {
            get {
                return ResourceManager.GetString("UserDetail_Gender_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su apellido es inválido.
        /// </summary>
        internal static string UserDetail_LastName_Invalid {
            get {
                return ResourceManager.GetString("UserDetail_LastName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su apellido.
        /// </summary>
        internal static string UserDetail_LastName_Required {
            get {
                return ResourceManager.GetString("UserDetail_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La concentración entrada es inválida.
        /// </summary>
        internal static string UserDetail_Major_Invalid {
            get {
                return ResourceManager.GetString("UserDetail_Major_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su inicial es inválida.
        /// </summary>
        internal static string UserDetail_MiddleInitial_Invalid {
            get {
                return ResourceManager.GetString("UserDetail_MiddleInitial_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rol entrado es inválido.
        /// </summary>
        internal static string UserDetail_Role_Invalid {
            get {
                return ResourceManager.GetString("UserDetail_Role_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El contenido de la nota es inválido.
        /// </summary>
        internal static string UserNote_Note_Invalid {
            get {
                return ResourceManager.GetString("UserNote_Note_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string UserNote_Note_Required {
            get {
                return ResourceManager.GetString("UserNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El correo electrónico ingresado ya esta en uso..
        /// </summary>
        internal static string User_Email_Exists {
            get {
                return ResourceManager.GetString("User_Email_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su correo electrónico es inválido.
        /// </summary>
        internal static string User_Email_Invalid {
            get {
                return ResourceManager.GetString("User_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un correo electrónico.
        /// </summary>
        internal static string User_Email_Required {
            get {
                return ResourceManager.GetString("User_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su número telefónico es inválido.
        /// </summary>
        internal static string User_PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("User_PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su contraseña es inválida. .
        /// </summary>
        internal static string User_UserPassword_Invalid {
            get {
                return ResourceManager.GetString("User_UserPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado contraseña.
        /// </summary>
        internal static string User_UserPassword_Required {
            get {
                return ResourceManager.GetString("User_UserPassword_Required", resourceCulture);
            }
        }
    }
}
