//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.WebResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string ActivityNote_Note_Required {
            get {
                return ResourceManager.GetString("ActivityNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el propósito de esta actividad.
        /// </summary>
        internal static string Activity_Purpose_Required {
            get {
                return ResourceManager.GetString("Activity_Purpose_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el título de esta actividad.
        /// </summary>
        internal static string Activity_Title_Required {
            get {
                return ResourceManager.GetString("Activity_Title_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su comentario.
        /// </summary>
        internal static string Feedback_Feedback_Required {
            get {
                return ResourceManager.GetString("Feedback_Feedback_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el enlace de este medio.
        /// </summary>
        internal static string Media_MediaPath_Required {
            get {
                return ResourceManager.GetString("Media_MediaPath_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado la misión de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Mission_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Mission_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado los objetivos de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Objectives_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Objectives_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el nombre de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_OutreachEntityName_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_OutreachEntityName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado la visión de la organización.
        /// </summary>
        internal static string OutreachEntityDetail_Vision_Required {
            get {
                return ResourceManager.GetString("OutreachEntityDetail_Vision_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un nombre para este recurso.
        /// </summary>
        internal static string Resource_ResourceName_Required {
            get {
                return ResourceManager.GetString("Resource_ResourceName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string SchoolNote_Note_Required {
            get {
                return ResourceManager.GetString("SchoolNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado una dirección para esta escuela.
        /// </summary>
        internal static string School_Address_Required {
            get {
                return ResourceManager.GetString("School_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un número telefónico para esta escuela.
        /// </summary>
        internal static string School_PhoneNumber_Required {
            get {
                return ResourceManager.GetString("School_PhoneNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el numero de identificación para esta escuela.
        /// </summary>
        internal static string School_SchoolSequenceNumber_Required {
            get {
                return ResourceManager.GetString("School_SchoolSequenceNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe una escuela con ese numéro de identificación.
        /// </summary>
        internal static string School_SchoolSequenceNumber_Unique {
            get {
                return ResourceManager.GetString("School_SchoolSequenceNumber_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su nombre.
        /// </summary>
        internal static string UserDetail_FirstName_Required {
            get {
                return ResourceManager.GetString("UserDetail_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su género.
        /// </summary>
        internal static string UserDetail_Gender_Required {
            get {
                return ResourceManager.GetString("UserDetail_Gender_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado su apellido.
        /// </summary>
        internal static string UserDetail_LastName_Required {
            get {
                return ResourceManager.GetString("UserDetail_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado el contenido de la nota.
        /// </summary>
        internal static string UserNote_Note_Required {
            get {
                return ResourceManager.GetString("UserNote_Note_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado un correo electrónico.
        /// </summary>
        internal static string User_UserEmail_Required {
            get {
                return ResourceManager.GetString("User_UserEmail_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ha ingresado contraseña.
        /// </summary>
        internal static string User_UserPassword_Required {
            get {
                return ResourceManager.GetString("User_UserPassword_Required", resourceCulture);
            }
        }
    }
}
