//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityNotes = new HashSet<ActivityNote>();
            this.ActivityResources = new HashSet<ActivityResource>();
            this.Contacts = new HashSet<Contact>();
            this.Documents = new HashSet<Document>();
            this.Feedbacks = new HashSet<Feedback>();
            this.Interests = new HashSet<Interest>();
            this.Media = new HashSet<Medium>();
        }
    
        public int ActivityID { get; set; }
        public int ActivityTypeID { get; set; }
        public int UserID { get; set; }

        [Required(ErrorMessageResourceName = "Activity_Title_Required", ErrorMessageResourceType = typeof(Resources.WebResources))]
        public string Title { get; set; }

        [Required(ErrorMessageResourceName = "Activity_Purpose_Required", ErrorMessageResourceType = typeof(Resources.WebResources))]
        public string Purpose { get; set; }

        public string Location { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string ActivityTime { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual ActivityType ActivityType { get; set; }
        public virtual ICollection<ActivityNote> ActivityNotes { get; set; }
        public virtual ICollection<ActivityResource> ActivityResources { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual ICollection<Medium> Media { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual School School { get; set; }
    }
}
