//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPDB.Models
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;

    public partial class Medium
    {
        public int MediaID { get; set; }
        public int ActivityID { get; set; }
        public string MediaType { get; set; }

        [RegularExpression(@"^[a-zA-Z\u00c0-\u017e''-'\s]{1,40}$", ErrorMessageResourceName = "Media_MediaTitle_Invalid", ErrorMessageResourceType = typeof(Resources.WebResources))]
        public string MediaTitle { get; set; }

        [RegularExpression(@"^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?$", ErrorMessageResourceName = "Media_MediaPath_Invalid", ErrorMessageResourceType = typeof(Resources.WebResources))]
        public string MediaPath { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
