//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Resources = new HashSet<Resource>();
        }
    
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public string Building { get; set; }
        public string RoomNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Extension { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UpdateUser { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
    
        public virtual ICollection<Resource> Resources { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
